name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Check Syntax
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      # You may pin to the exact commit or the version.
      # uses: zhxiaogg/cargo-static-build@c73ebfef9174ddf30a8949280b756f87e00904e4
      uses: zhxiaogg/cargo-static-build@v1.41.1-1
      with:
        # build command
        cmd: cargo build # default is cargo build
        run: cargo build --verbose --release

