name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Check Syntax
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      uses: zhxiaogg/cargo-static-build@v1.41.1-1
      with:
        run: cargo build --verbose --release

